

#  Stores all the constants for this module

# A list of exchanges for which the screener should scan stock data
ex_baselist = {
    'mic': [
        "XNYS",
        "XNAS",
        "XJPX",
        "XLON",
        "XMIL",
        "XSHG",
        "XHKG",
        "XAMS",
        "XBRU",
        "XMSM",
        "XLIS",
        "XOSL",
        "XPAR",
        "XTSE",
        "XSHE",
        "XBOM",
        "XNSE",
        "XFRA",
        "XSWX",
        "XKOS",
        "XCSE",
        "XSTO",
        "XHEL",
        "XTAL",
        "XRIS"],
    'rank': [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25]
}
